# Generated by Django 3.0 on 2019-12-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20191213_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='category',
        ),
    ]
