# Generated by Django 3.0 on 2019-12-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_list_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='person',
        ),
    ]
