# Generated by Django 3.0 on 2019-12-16 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_category_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todo.Category'),
        ),
    ]
